line-length = 120

[lint]
select = [
  "I",   # isort
  "UP",  # pyupgrade
  "B",   # bugbear
  "N", # naming conventions
  "S", # security
  "A", # builtins
  "ASYNC", # async best practices
  "E", "W", # pycodestyle
  "F", # pyflakes
  "SIM", # simplify
  "PT", # pytest
  "TD", # todo
  "NPY", # numpy
  "TC", # type-checking
  "PTH", # pathlib
  "TID", # import practices
  "C4", # comprehensions
  "FA", # from __future__ import annotations
  "ISC", # string concatenation
  "ICN", # common import conventions
  "RET", # good return practices
]

ignore = [
    "E501", # Line too long (handled by formatter)

    # reserved for future use if ANN or F rules are added to select:
    "ANN101", "ANN102", "ANN401",
]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
"__init__.py" = ["F401"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

