line-length = 79
indent-width = 4


[lint]
select = [
  "A",
  "AIR",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "CPY",
  "DOC",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "EXE",
  "F",
  "FAST",
  "FBT",
  "FIX",
  "FLY",
  "FURB",
  "G",
  "I",
  "ICN",
  "INT",
  "INP",
  "ISC",
  "LOG",
  "N",
  "NPY",
  "PD",
  "PERF",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "T20",
  "TC",
  "TD",
  "TID",
  "TRY",
  "UP",
  "RUF",
  "W",
  "YTT",
]

ignore = ["E501", "ANN101", "ANN102", "ANN401", "ISC001"]

[lint.per-file-ignores]
"asteroidfield.py" = ["S311"]
"asteroid.py" = ["S311"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
